### ISSUE TITLE
Implement first version of generalize method

### ISSUE THREAD

**Issue by jirik** [gis4dis/cg#1]
Implement first version of [generalize](https://github.com/gis4dis/poster/wiki/Interface-between-MC-client-&-CG#generalize) method.

The first version will only assign styles to the features (no generalization needed).

**Comment by Bulva** [comment]
Commit 04589f2fa5b8f927fe1520ab1c4271ee9d84c92e

Things to discussion:
- Real example of parameters for generalize function
- Are properties also vector layers?
- What about unit tests? Tried Jasmine but there are problems with ES6 import and export syntax
- Code structure can be changed based on things resulting from real example of the data. It must be maintainable and modular as much as possible because of a lot of others functionality related to CBR will be added.

**Comment by Bulva** [comment]
Commit c3e74d7423a534ffe5fd5a9078531eb9aacae766: Added SVG icons support

Things to do on tomorrow:

- ~~cleaning the imports~~ (9bd0683f2dfaf4682f95e264ed7ec1f33dadcdd5)
- ~~updating JSDoc~~ (38d40d35c16749f7b90c6a0d127214ca08a5cdbb)
- ~~add assurance for length of the property values~~ (9bd0683f2dfaf4682f95e264ed7ec1f33dadcdd5)

Things to do in near future:
- **add labels with values (for discussion)**
- ~~writing some tests~~ (partially 3af1590e1549268fd1ff6317679962b3d7109b42, partially a84cf8f702bf145f9fe30508df33da43e54b3343, dfbeed78e05dec52aeb3de66695a1ab3d86e0263)
- ~~**normalizing values for columns**~~ (3af1590e1549268fd1ff6317679962b3d7109b42)
  - ~~SOLUTION~~ 
    - ~~normalizing values for bbox (different units)~~ 
- **add shift value (probably better to wait for a real example)**
- symbol for temperature  (negative values)
- ~~**implement resolution**~~ (a84cf8f702bf145f9fe30508df33da43e54b3343)

Things to do in future (maybe):
- collision resolver?

## Results of discussion (Karel)
- Visualization of anomaly rates (color) - values from 0 to 1
- Crossreference (other symbol e.g. circle)
- Find the way how symbolize feature after clustering (points -> polygon)
- Identification of "clusters" based on distance and shape of points
- **More properties in one function call** - we need compare values and provide the most important thing for the user
- Normalizing values for bbox or bigger area?
- ~~4326 or 3857~~
